### ISSUE TITLE
Allow working without etensions

### ISSUE THREAD

**Issue by grosser** [mcrossen/deepsort#6]
I'd prefer to use `Deepsort.sort(hash)` ... would you accept a PR to make this available ?
... what are you thoughts about making that the default and having a separate file like `deepsort/ext` do the patching ?

@mcrossen

**Comment by mcrossen** [comment]
Any PRs for this repository are very welcome. Adding support for Deepsort.sort() seems like a good idea to me, but having a separate file for patching could break existing projects that depend on the current default behavior.
